### ISSUE TITLE
Streaming disconnects immediately when using Workbench with API v37

### ISSUE THREAD

**Issue by john-brock** [forceworkbench/forceworkbench#687]
Using v37, streaming handshake succeeds, but a disconnect happens immediately, even though the initial handshake and connect are successful. The client id in the requests/responses are expected, but Salesforce is returning a 403 Unknown client error with the disconnect message.

**Comment by ozzieg** [comment]
I am seeing this issue as well. Any ETA or workaround?

**Comment by john-brock** [comment]
The workaround is to use API V36 of workbench. 

In the right hand corner, click on link that says {Name} at {Org} on API 37, change API version to 36, then using streaming as expected. 
This workaround will not allow you to use Streaming V2 with the event replay functionality, but all other streaming operations will work. I am currently working to find the root cause and will then implement a fix.

**Comment by ozzieg** [comment]
Thanks! I figured that out as well.

**Comment by JeffFarnsworth** [comment]
@john-brock Were you able to find a solution to this problem?  I'm still running into it when using the Workbench and following the documentation.  Would really like to have Replay working for PushTopics with API v37 as intended!

**Comment by RoyGilad** [comment]
Thanks for the workaround @john-brock !

**Comment by durp** [comment]
Any update on this? It is a rather nasty problem; the tutorials all rely on this actually working.

**Comment by john-brock** [comment]
@durp @JeffFarnsworth I am still looking into this. I have added various logging and am trying to diagnose whether the issue is on the workbench or Salesforce side. In the mean time, be sure to check out https://github.com/developerforce/SalesforceDurableStreamingDemo which is a VF durable streaming sample for push-topic and generic streaming.

**Comment by hemangajmera** [comment]
I found one more issue with version 36. If there are more than one data pushed, then version 36, only shows 1 data, and not others. 

Here is how response with v36 looks like...

{clientId=46wv831cxwxhre91k5lenc0io2nf, data={event={createdDate=2018-04-18T15:03:32.000+0000, type=updated}, sobject={Sales_Organization__c=CEO, OwnerId=005580000010NGiAAM, Id=0019E00000WxZttQAF}}, channel=/topic/AccountOwners}


Here is how the response with v37 ... v41 looks like for similar event!

[{data={event={createdDate=2018-04-18T14:03:54.119Z, replayId=18729, type=updated}, sobject={Sales_Organization__c=CEO,  OwnerId=00558000001vZOPAA2, Id=0019E00000WxZttQAF}}, channel=/topic/AccountOwners}, {data={event={createdDate=2018-04-18T14:03:54.509Z, replayId=18730, type=updated}, sobject={Sales_Organization__c=CEO, OwnerId=00558000001vZOPAA2, Id=0019E00000WxZttQAF}}, channel=/topic/AccountOwners}, {clientId=8itdrw6jzgh863l1ojsrwp0ut6ws, channel=/meta/connect, id=3, successful=true}]

We were not able to see that salesforce is sending out duplicate event in workbench since it is using version 36.

**Comment by tcho16** [comment]
Is there any update on this? I followed the durable stream demo but still facing this issue
