### ISSUE TITLE
On submitting credentials while login, fails with "Call to undefined function sodium_crypto_box() "

### ISSUE THREAD

**Issue by aishwaryak** [forceworkbench/forceworkbench#804]
Full error: 
" Fatal error: Call to undefined function sodium_crypto_box() in /var/www/html/workbench/shared.php on line 705".

I'm on Ubuntu 14.04, and have libsodium installed.

**Comment by Amit-Tripathi** [comment]
i am facing the same error on windows 10. I installed wamp and followed the instructions and put the folder in the root.

Do we have any directions to resolve it.

**Comment by Krisa** [comment]
The error is caused because you probably commented out the /vendor/autoload.php file in the shared.php (which is missing) ... and this function was referenced in the vendor/autoload.php so that's the next error.

It feels like workbench is not supported anymore running on php out of the box.

To fix the error, I've used an older version of shared.php which was not referencing this external dependency. The rest seems to work.

**Comment by aishwaryak** [comment]
Yeah @Krisa you're right it was because I commented out the line for autoload.php. Do you mind sharing the shared.php version that you were using, that fixes this? Thanks in advance!

**Comment by Krisa** [comment]
https://gist.github.com/Krisa/893bc8932166b7aaa34c9ba8ffc86fee

**Comment by shintynash** [comment]
@Krisa @aishwaryak If you install the Sodium Extension, and add revert to teh original shared.php with the /vendor/autoload.php line things should work. If you use WAMPServer it's pretty easy to install. Click on Taskbar icon -> PHP -> PHP Extensions -> Sodium
